### ISSUE TITLE
How to suspend the moving of the Cartpole?

### ISSUE THREAD

**Issue by Fleer-code** [inkyusa/raisimGymTutorial#4]
Hello. After I check 'simulation' --> 'manual stepping' in the menu in test mode. The cartpole does not stop moving. Is there anything I can do to suspend it?

**Comment by jhwangbo** [comment]
Hi Fleer-code. The gui in RaisimGym is actually not for training. It only works in raisimOgre. The manual stepping code has to be implemented on raisimGym side since that's where you control stepping.

One way is to make a wait function in your Environment::Step() so that it just waits if the flag from the gui is on.

There are many different ways to set up a gui for training and you have to customize it to satisfy your needs.
